djangoProject/djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

djangoProject/myapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from myapp import views

app_name = 'myapp'

urlpatterns = [path(r'', views.index, name='index'),
               path(r'about', views.about, name='about'),
               path(r'<int:topic_id>', views.detail, name='detail'),
               path(r'findcourses', views.findcourses, name='findcourses'),
               path(r'place_order', views.place_order, name='place_order'),
               path(r'review', views.review, name='review'),
               path(r'login', views.user_login, name='user_login'),
               path(r'logout', views.user_logout, name='user_logout'),
               path(r'myaccount', views.myaccount, name='myaccount'),
               path(r'myorders', views.myorders, name='myorders'),
               path(r'register', views.register, name='register'),
               ]

djangoProject/myapp/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    length = models.IntegerField(default=12, blank=False)

    def __str__(self):
        return self.name


class Course(models.Model):
    title = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                validators=[MinValueValidator(50.0), MaxValueValidator(500.0)])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Student(User):
    LVL_CHOICES = [
        ('HS', 'High School'),
        ('UG', 'Undergraduate'),
        ('PG', 'Postgraduate'),
        ('ND', 'No Degree'),
    ]
    level = models.CharField(choices=LVL_CHOICES, max_length=2, default='HS')
    address = models.CharField(max_length=300, blank=True)
    province = models.CharField(max_length=2, default='ON')
    registered_courses = models.ManyToManyField(Course, blank=True)
    interested_in = models.ManyToManyField(Topic)
    user_image = models.ImageField(upload_to='images/', blank=True)


class Order(models.Model):
    STATUS_CHOICES = [(0, 'Cancelled'), (1, 'Confirmed'), (2, 'On Hold')]
    courses = models.ManyToManyField(Course)
    student = models.ForeignKey(Student, related_name="Orders", on_delete=models.CASCADE)
    order_date = timezone.now()
    order_status = models.IntegerField(default=1, choices=STATUS_CHOICES)

    def total_cost(self):
        cost = 0
        for course in self.courses.all():
            cost += course.price
        return cost

    def total_items(self):
        return self.courses.all().count()


class Review(models.Model):
    reviewer = models.EmailField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True)
    date = models.DateField(default=timezone.now)

djangoProject/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from myapp.models import Order, Review, Student


class SearchForm(forms.Form):
    LENGTH_CHOICES = [
        (8, '8 Weeks'),
        (10, '10 Weeks'),
        (12, '12 Weeks'),
        (14, '14 Weeks'),
    ]
    name = forms.CharField(max_length=100, required=False, label="Student Name")
    length = forms.TypedChoiceField(widget=forms.RadioSelect,
                                    choices=LENGTH_CHOICES, coerce=int, required=False)
    max_price = forms.IntegerField(label="Maximum Price", min_value=0)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['courses', 'student', 'order_status']
        widgets = {'courses': forms.CheckboxSelectMultiple(),
                   'order_type': forms.RadioSelect}
        labels = {'student': u'Student Name', }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'course', 'rating', 'comments']
        widgets = {'courses': forms.RadioSelect()}
        labels = {'reviewer': 'Please enter a valid email', 'rating': 'Rating: An integer between 1 (worst) and 5 ('
                                                                      'best)'}


class RegisterForm(UserCreationForm):
    class Meta:
        model = Student
        fields = ['user_image', 'username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'level',
                  'address', 'province', 'registered_courses',
                  'interested_in']

djangoProject/myapp/views.py
from urllib.parse import urlparse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.datetime_safe import datetime

from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm
from .models import Topic, Course, Student


def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]

    if request.session.has_key('last_login'):
        login_detail = request.session['last_login']
        return render(request, 'myapp/index.html', {'top_list': top_list, 'last_login': login_detail})
    return render(request, 'myapp/index.html', {'top_list': top_list})


def about(request):
    about_us = "This is an E-learning Website! Search our Topics to find all available Courses."
    if request.session.has_key('about_visits'):
        request.session['about_visits'] = request.session['about_visits'] + 1
        request.session.set_expiry(300)
    else:
        request.session['about_visits'] = 1
        request.session.set_expiry(300)
    return render(request, 'myapp/about.html', {'about_us': about_us, 'num_times': request.session['about_visits']})


def detail(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)

    cour_list = topic.courses.all()
    return render(request, 'myapp/detail.html', {'topic': topic, 'cour_list': cour_list})


def findcourses(request):
    # breakpoint()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            length = form.cleaned_data['length']
            max_price = form.cleaned_data['max_price']
            if not length:
                topics = Topic.objects.all().filter(courses__price__lte=max_price)
            else:
                topics = Topic.objects.filter(length=length).filter(courses__price__lte=max_price)

            courselist = []
            for top in topics:
                courselist = courselist + list(top.courses.all())
            return render(request, 'myapp/results.html',
                          {'courselist': courselist, 'name': name})
        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, 'myapp/findcourses.html', {'form': form})


def place_order(request):
    if request.method == 'POST':
        stu = Stu
        if stu.count() == 0:
            return render(request, 'myapp/myorders.html', {'message': "You're not a registered student."})
        else:
            return render(request, 'myapp/myorders.html', {'orders': stu.get().Orders.all()})
        form = OrderForm(request.POST)
        if form.is_valid():
            courses = form.cleaned_data['courses']
            order = form.save(commit=True)
            student = order.student
            status = order.order_status
            order.save()
            if status == 1:
                for c in order.courses.all():
                    student.registered_courses.add(c)
            return render(request, 'myapp/order_response.html', {'courses':
                                                                     courses, 'order': order})
        else:
            return render(request, 'myapp/place_order.html', {'form': form})
    else:
        form = OrderForm()
        return render(request, 'myapp/place_order.html', {'form': form})


def review(request):
    user = request.user
    stu = Student.objects.filter(pk=user.pk)
    if stu.count() == 0 or (stu.get().level != 'UG' and stu.get().level != 'PG'):
        return render(request, 'myapp/review.html', {'message': "You're  not Student or not an Undergraduate or "
                                                                "Postgraduate."})
    else:
        if request.method == 'POST':
            form = ReviewForm(request.POST)

            if form.is_valid():
                rating = form.cleaned_data['rating']
                if 0 < rating < 5:
                    rev = form.save(commit=True)
                    rev.rating = rating

                    rev.reviewer = form.cleaned_data['reviewer']
                    rev.course.num_reviews = rev.course.num_reviews + 1
                    rev.course.save()
                    return redirect('myapp:index')
                else:
                    return render(request, 'myapp/review.html', {'form': form, 'message': 'You must enter a rating '
                                                                                          'between 1 and 5!'})
            else:
                return render(request, 'myapp/review.html', {'form': form})
        else:
            form = ReviewForm()
            return render(request, 'myapp/review.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        next_url = request.POST.get('next')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)
                request.session['last_login'] = str(datetime.now())
                request.session.set_expiry(3600)
                if next_url:
                    return HttpResponseRedirect(next_url)
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required(login_url="myapp:user_login")
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required(login_url="myapp:user_login")
def myaccount(request):
    user = request.user

    stu = Student.objects.filter(pk=user.pk)

    if stu.count() == 0:
        return render(request, 'myapp/myaccount.html', {'message': "You're not a registered student."})
    else:
        return render(request, 'myapp/myaccount.html',
                      {'first_name': stu.get().first_name, 'last_name': stu.get().last_name,
                       'topics': stu.get().interested_in.all(), 'courses': stu.get().registered_courses.all(),
                       "image": stu.get().user_image.url})


@login_required
def myorders(request):
    user = request.user
    stu = Student.objects.filter(pk=user.pk)
    if stu.count() == 0:
        return render(request, 'myapp/myorders.html', {'message': "You're not a registered student."})
    else:
        return render(request, 'myapp/myorders.html', {'orders': stu.get().Orders.all()})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            myfile = request.FILES['user_image']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            courses = form.cleaned_data['registered_courses']
            topics = form.cleaned_data['interested_in']
            stu = Student.objects.get(username=username)
            for c in courses:
                stu.registered_courses.add(c)
            for t in topics:
                stu.interested_in.add(t)
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('myapp:index')

    else:
        form = RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})

djangoProject/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{%  block title %}
APP About page
{% endblock %}
{% block body_block %}
{% if about_us %}
<h2>{{ about_us }}</h2>
{% endif %}
{% if num_times %}
<h2>{{ num_times }}</h2>
{% endif %}
<a href="{% url 'myapp:index' %}">Back to the main page.</a></p>
{% endblock %}

djangoProject/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Page</title>
</head>
<body>
{% if about_us %}
<h2>{{ about_us }}</h2>
{% endif %}
<p><a href="/myapp">Index page - Hardcoded</a>
    <a href="{% url 'myapp:index' %}">Index page - URL Namespacing</a></p>
</body>
</html>

djangoProject/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link href="{% static 'myapp/style1.css' %}" rel="stylesheet" type="text/css"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" rel="stylesheet">
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8 mt-5">
            {% if user.is_authenticated %}
            {% if request.user.user_image %} <img alt="Profile" request.user.user_image.url src={{ }}/>{% endif %}
            <h1>Hello {{ request.user.first_name }}</h1>
            {% block body_block %}*** {% endblock %}
            <ol class="nav col-16">
                <li class="col-2"><h3><a class="btn mt-2 btn-primary" href="{% url 'myapp:review' %}">Add a review</a>
                </h3></li>
                <li class="col-2"><h3><a class="btn mt-2 btn-primary" href="{% url 'myapp:myaccount' %}">My Account</a>
                </h3></li>
                <li class="col-1"><h3><a class="btn mt-2 btn-primary" href="{% url 'myapp:myorders' %}">My Orders</a>
                </h3></li>
                <li class="col-10"><h3><a class="btn mt-2 btn-danger" href="{% url 'myapp:user_logout' %}">Logout!</a>
                </h3></li>
            </ol>
            {% else %}
            {% block login_block %}
            <h2>You're not logged in.</h2>
            <a class="btn mt-2 btn-success"
               href="{% url 'myapp:user_login' %}?next={{ request.GET.next }}">Login</a><br/>
            <a class="btn mt-2 btn-success" href="{% url 'myapp:register' %}">Register</a>

            {% endblock %}
            {% endif %}


            <hr/>
            <div>
                <ul>
                    <li class="hbar1"><a class="btn btn-link" href="{% url 'myapp:about' %}">Find out about this
                        site</a></li>
                    <li class="hbar1"><a class="btn btn-link" href="{% url 'myapp:findcourses' %}">Search Courses</a>
                    </li>
                    <li class="hbar1"><a class="btn btn-link" href="{% url 'myapp:index' %}">Return to main
                        page</a><br/></li>
                </ul>
            </div>
        </div>
    </div>
</div>
</body>
</html>

djangoProject/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{%  block title %}
{{ topic }} page
{% endblock %}
{% block body_block %}
{% if topic%}
<h2>
    Name: {{ topic }} <br/>
    Length: {{ topic.length }}
</h2>
{% if cour_list %}
<h3>List of the Courses:</h3>
<ol>
    {% for cour in cour_list %}
    <li> {{ cour }}</li>
    {% endfor %}
</ol>
{% endif %}
{% endif %}
{% endblock %}

djangoProject/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ topic }}</title>
</head>
<body>
{% if topic%}
<h2>
    Name: {{ topic }} <br/>
    Length: {{ topic.length }}
</h2>
{% if cour_list %}
<h3>List of the Courses:</h3>
<ol>
    {% for cour in cour_list %}
    <li> {{ cour }}</li>
    {% endfor %}
</ol>
{% endif %}
{% endif %}
<p><a href="{% url 'myapp:index' %}">Go Back</a></p>
</body>
</html>

djangoProject/myapp/templates/myapp/findcourses.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<form action="{% url 'myapp:findcourses' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input name="submit1" type="submit" value="Find Courses"/>
</form>
{% endblock %}

djangoProject/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
{% if last_login %}
{{ last_login }}
{% if top_list %}
<h2>List of Topics</h2>
<ol>
    {% for top in top_list %}
    <li><a href="{% url 'myapp:detail' top.id %}">{{ top.name }}</a></li>
    {% endfor %}
</ol>
<p><a href="{% url 'myapp:place_order' %}">Place Order</a></p>
{% else %}
<strong>There are no available topics!</strong>
{% endif %}
{% else %}
<h2>Your last login was an hour ago.</h2>
{% endif %}

{% endblock %}

djangoProject/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
{% if top_list %}
<h2>List of Topics</h2>
<ol>
    {% for top in top_list %}
    <li> {{ top.name }}</li>
    {% endfor %}
</ol>
{% else %}
<strong>There are no available topics!</strong>
{% endif %}
<p><a href="{% url 'myapp:about' %}">About page</a></p>
</body>
</html>

djangoProject/myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
{% block myhdg %} {{ first_name }} {% endblock %}
{% block body_block %}
{% if message %}
<h2>{{ message }}</h2>
{% elif first_name %}
{% if image %} <img alt="Profile" class="img-thumbnail" height="160px"
                    src="{{image}}" style="vertical-align:middle" width="200px"/>{% endif %}
<h2>Name: {{ first_name }} {{ last_name }}</h2>
<h3>List of the Topics:</h3>
<ol>
    {% for top in topics %}
    <li> {{ top }}</li>
    {% endfor %}
</ol>

<h3>List of the Courses:</h3>
<ol>
    {% for cour in courses %}
    <li> {{ cour }}</li>
    {% endfor %}
</ol>
{% endif %}


{% endblock %}

djangoProject/myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block body_block %}
{% if message %}
<h2>{{ message }}</h2>
{% elif orders %}
<h3>List of the Orders:</h3>
<ol>
    {% for order in orders %}
    <li> {{ order }}</li>
    {% endfor %}
</ol>
{% else %}
<h3>No order placed yet.</h3>
{% endif %}

{% endblock %}

djangoProject/myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<form action="{% url 'myapp:place_order' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input name="submit1" type="submit" value="Place Order"/>
</form>
{% endblock %}

djangoProject/myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block login_block %}
<h2>Register</h2>
<form action="{% url 'myapp:register' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button class="btn mt-2 btn-success" type="submit">Register</button>
</form>
{% endblock %}

djangoProject/myapp/templates/myapp/results.html
{% extends 'myapp/base.html' %}
{% block myhdg %}{{ name }} {% endblock %}
{% block body_block %}
{% if courselist %}
<h3>List of the Courses found:</h3>
<ol>
    {% for cour in courselist %}
    <li> {{ cour }}</li>
    {% endfor %}
</ol>
{%  else %}
No Courses found.
{% endif %}
{% endblock %}

djangoProject/myapp/templates/myapp/review.html
{% extends 'myapp/base.html' %}
{% block body_block %}
{%  if message %}
<h3 style="color:red">{{ message }}</h3>
{% endif %}
<form action="{% url 'myapp:review' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input name="submit1" type="submit" value="Review"/>
</form>
{% endblock %}